[package]
name = "poros"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = { version = "0.11.0", features = ["storage"] }
wasm-bindgen = "0.2.100"
yew = { version = "0.21.0", features = ["csr"] }
